services:
    ## Renderer
    CoreShop\Bundle\IndexElasticBundle\Order\Elasticsearch\AbstractElasticsearchDynamicRenderer:
        abstract: true
        arguments:
            - '@doctrine.dbal.default_connection'

    CoreShop\Bundle\IndexElasticBundle\Order\Elasticsearch\SimpleOrderRenderer:
        parent: CoreShop\Bundle\IndexElasticBundle\Order\Elasticsearch\AbstractElasticsearchDynamicRenderer
        tags:
            - { name: coreshop.index.order.renderer, type: elastic_simple }

